version: '3'
services:
  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    env_file: 
      - ./docker/server/.env.development
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}/server:/server:z
    stdin_open: true
    tty: true
  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    env_file: 
      - ./docker/client/.env.development
    ports:
      - "8080:8080"
    volumes:
      - ${PWD}/client:/client:z
    stdin_open: true
    tty: true
  pg:
    build:
      context: .
      dockerfile: ./docker/pg/Dockerfile
    env_file: 
      - ./docker/pg/.env.development
    restart: on-failure
    volumes:
      - ${PWD}/tmp/pg:/bitnami/postgresql
  mongo:
    build:
      context: .
      dockerfile: ./docker/mongo/Dockerfile
    env_file: 
      - ./docker/mongo/.env.development
    restart: on-failure
    volumes:
      - ${PWD}/tmp/mongo:/data/db
  redis:
    build:
      context: .
      dockerfile: ./docker/redis/Dockerfile
    env_file: 
      - ./docker/redis/.env.development
    restart: on-failure
    volumes:
      - ${PWD}/tmp/redis:/bitnami/redis/data
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    restart: on-failure
    ports:
      - "80:80"
    links:
      - server
      - client
